### ISSUE TITLE
Clarification on use of environment variables

### ISSUE THREAD

**Issue by flber** [digitalocean/sample-functions-golang-presigned-url#4]
I've been trying to figure out how to properly deploy a function with environment functions, but the documentation seems to be slightly unclear? In this repository the `.env` file has variable definitions, but how are they evaluated in the `project.yml` file? They seem to be defined using environment variable substitution, but testing locally with my desired variables set in my shell environment I'm given the error `Error: The following substitutions could not be resolved: 'GOOGLE_API_KEY'` 

My project.yml file is essentially just pulled from the default example:
```
parameters: {}
environment:
  GOOGLE_API_KEY: ${GOOGLE_API_KEY}
packages:
  - name: main
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
    - name: hello
      binary: false
      main: ""
      runtime: "go:1.20"
      web: true
      webSecure: false
      parameters: {}
      environment: {}
      annotations: {}
      limits: {}
```

and my project structure is pretty minimal
```
.
├── hello_test.go
├── packages
│   └── main
│       ├── .env
│       ├── go.mod
│       ├── go.sum
│       └── hello.go
└── project.yml
```
with `.env` just including the definition `GOOGLE_API_KEY="..."`
